<!doctype html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
              rel="stylesheet" 
              integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" 
              crossorigin="anonymous">

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" 
                integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" 
                crossorigin="anonymous"></script>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

        <link href="css/map.css" rel="stylesheet" type="text/css" />

        <title>RouteDevices</title>
    </head>

    <script>
        $( document ).ready(function() {

            $("#go_map").click(function(){
                $(".hideable").hide()
                $(".ring").show("quick", function(){
                    setTimeout(function(){
                        document.location.href="/Map/2";
                    }, 1000);
                });
            });
            //END ON READY
        });
    </script>

    <body>
    
        <div class='container-fluid vh-100 leFont main-cotainer'>
            <div class='row justify-content-md-center'>
                <div class='col-4 hideable'><h1>EnRutame<h2></div>
            </div>

            <div class='row justify-content-md-center mt-4'>
                <div class='col-6 hideable'>¿No conoces el edificio y quieres llegar a tu destino?</div>
                <div class="col-4"></div>
            </div>
            <div class='row justify-content-md-center mt-4'>
                <div class='col-6 hideable'>¡Solo con tu movil, sin Apps ni ostias!</div>
                <div class="col-4"><div class="leButton hideable" id="go_map">VAMOS</div></div>
            </div>

            <div class="ring leFont"><label id="loaderText">Loading</label><span id="lineLoader"></span></div>
        </div>

    </body>
    

</html>