<!doctype html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
              rel="stylesheet" 
              integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" 
              crossorigin="anonymous">

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" 
                integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" 
                crossorigin="anonymous"></script>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

        <link href="../css/map.css" rel="stylesheet" type="text/css" />

        <title>RouteDevices</title>

    </head>
    
    <script>
        $( document ).ready(function() {

            $("#closeForm").click(function(){ resetForm(); });

            $("#registerMobile").click(function(){
                $(this).hide(function(){$(".ring").show();});
                $.ajax({
                    url: "../RegisterDevice",
                    headers: { "cache-control": "no-cache" },
                    type: "POST",
                    data: {destiny : $("#routeDestiny").text() },
                    dataType: "json",
                }).done(function(response){
                    //console.log(response);
                    if(response.success){
                        $("#lineLoader, .ring").addClass("hidden");
                        
                        $("#loaderText").text('Listo').promise().done(function(){

                            setTimeout(function () {
                                $(".ring").hide(function(){
                                    $(".arrow").show();
                                }) 
                            }, 2000);

                            
                        });
                    }
                    else{
                        alert("Error al procesar la solicitud");
                    }
                })
                .fail(function(response){ alert("Error en el servidor, no pudo procesarse la solicitud") })
                .always(function(){ });
            });


            width = $(window).width();
            height = $(window).height();

            //Populate Areas
            $.ajax({url: "../MapAreas/<?=$floor?>"})
            .done(function(response){
                    if(response.length){
                        $("#mapImg").prop("src","../images/"+response[0].name+".png");

                        var areas = JSON.parse(response[0].areas);
                        $.each(areas, function(sala, area){
                            //console.log(area);
                            var href = "#";
                            switch(sala) {
                            case "0":
                                sala = "Estas Aquí"
                                break;
                            case "d":
                                href = "../Map/1";
                                sala = "Piso 1";
                                break;
                            default:
                                sala = 'sala ' +sala;
                            }
                            var mapZone = $('<area class="mapZone" href="'+href+'" shape="rect" alt="'+sala+'" coords="'+area.join()+'">')
                                          .click(function(){
                                            if(sala.indexOf("sala") === -1){
                                                return;
                                            }
                                            $("#formContainer").show();
                                            $('.fog').css('display', 'block');
                                            $("#routeDestiny").text(sala);
                                          });

                            $("#mapper").append( mapZone );
                        });
                    }
                    else{
                        alert("Mapa no disponible");
                    }
                })
                .fail(function(response){ alert("Error en el servidor, no pudo obtenerse las areas") })
                .always(function(){

                    $("area").each(function() {
                        var txt = $(this).attr('alt');
                        var textSize = txt.length * 15;
                        var pairs = $(this).attr("coords").split(', ');
                        for(var i=0; i<pairs.length; i++) {
                            var nums = pairs[i].split(',');
                            for(var j=0; j<nums.length; j++) {
                                //original img have 1301 x 712
                                if(i == 0 || i == 2){
                                    nums[j] = Math.floor(nums[j] * width / 1301);
                                }
                                else{
                                    nums[j] = Math.floor(nums[j] * height / 712);
                                }
                            }
                            var leftTextCoor= Math.floor( ((nums[0] + nums[2]) / 2) - (textSize / 3 ));
                            var topTextCoor= Math.floor((nums[1] + nums[3]) / 2);

                            pairs[i] = nums.join(',');
                        }

                        $(this).attr("coords", pairs.join(', '));
                        var span=$('<span class="leFont">'+txt+'</span>');        
                        span.css({top: topTextCoor+'px', left: leftTextCoor+'px', position:'absolute'});
                        span.appendTo($(this));
                    });


                });
            
            //End Onready
        });

        //IddelTime Controller
        (function() {
            const idleDurationSecs = 60;    // X number of seconds
            let idleTimeout; // variable to hold the timeout, do not modify
            const resetIdleTimeout = function() {

                // Clears the existing timeout
                if(idleTimeout) clearTimeout(idleTimeout);

                // Set a new idle timeout to load the redirectUrl after idleDurationSecs
                idleTimeout = setTimeout(() => location.href = '/', idleDurationSecs * 1000);
            };

            // Init on page load
            resetIdleTimeout();

            // Reset the idle timeout on any of the events listed below
            ['click', 'touchstart', 'mousemove'].forEach(evt => 
                document.addEventListener(evt, resetIdleTimeout, false)
            );

            })();

        function resetForm(){
            $("#formContainer,.arrow, .ring").hide();
            $("#loaderText").text('Scaning')
            $("#lineLoader, .ring").removeClass("hidden");
            $("#registerMobile").show();
            $('.fog').css('display', 'none');
        }
    </script>


    <body>
        <div class="fog"></div>

        <div class="container-fluid vh-100 pt-4">
            <div id="map-img">
                <img id="mapImg" src="" alt="mapa" style='width: 100%' usemap="#mapper">
                <map id="mapper" name="mapper"></map>
            </div>
        </div>

        <div id="formContainer" class="container leFont">

            <div class="row justify-content-end m-4">
                <div class="col-6 align-self-center">Destino: <span id="routeDestiny"><span></div>
                <div class="col-1 align-self-end"><img id="closeForm" src="../images/cancel.png" alt="cerrar"></div>
            </div>

            <div class="row m-4">
                <div class="col-8">1º) Activa el Bluethood<span><img src="../images/bluetooth.png" alt="bluethood" style='vertical-align: sub;'></span> de tu movil.</div>
                
            </div>
            <div class="row m-4">
                <div class="col-8">2º) Acercalo a esta pantalla.</div>
            </div>

            <div class="row m-4">
                <div class="col-7">3º) Pulsa el botón y manten el movil cerca hasta que este listo.</div>
                <div class="col-3"><div id="registerMobile" class="leButton">Escaneame</div></div>
            </div>

            <div class="ring leFont"><label id="loaderText">Scaning</label><span id="lineLoader"></span></div>
            <div class="arrow"></div>

        </div>


    </body>
    

</html>