<!doctype html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
              rel="stylesheet" 
              integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" 
              crossorigin="anonymous">

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" 
                integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" 
                crossorigin="anonymous"></script>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

        <link href="css/map.css" rel="stylesheet" type="text/css" />

        <title>RouteDevices</title>

    </head>
    
    <script>
        $( document ).ready(function() {

            width = $(window).width();
            height = $(window).height();

            $("area").each(function() {
                
                var txt = $(this).attr('alt');
                var textSize = txt.length * 15;
                var pairs = $(this).attr("coords").split(', ');
                for(var i=0; i<pairs.length; i++) {
                    var nums = pairs[i].split(',');
                    for(var j=0; j<nums.length; j++) {
                        //original img have 1301 x 712
                        if(i == 0 || i == 2){
                            nums[j] = Math.floor(nums[j] * width / 1301);
                        }
                        else{
                            nums[j] = Math.floor(nums[j] * height / 712);
                        }
                    }
                    var leftTextCoor= Math.floor( ((nums[0] + nums[2]) / 2) - (textSize / 3 ));
                    var topTextCoor= Math.floor((nums[1] + nums[3]) / 2);

                    pairs[i] = nums.join(',');
                }

                $(this).attr("coords", pairs.join(', '));
                var span=$('<span class="leFont">'+txt+'</span>');        
                span.css({top: topTextCoor+'px', left: leftTextCoor+'px', position:'absolute'});
                span.appendTo($(this));
            });
            

            
            $(".mapZone").click(function(){
                $("#formContainer").show();
                $('.fog').css('display', 'block');
                $("#routeDestiny").text($(this).attr("alt"));
            });

            $("#closeForm").click(function(){ resetForm(); });

            $("#registerMobile").click(function(){
                $(this).hide(function(){$(".ring").show();});
                $.ajax({
                    url: "RegisterDevice",
                    headers: { "cache-control": "no-cache" },
                    type: "POST",
                    data: {destiny : $("#routeDestiny").text() },
                    dataType: "json",
                }).done(function(response){
                    console.log(response);
                    if(response.success){
                        $("#lineLoader, .ring").addClass("hidden");
                        
                        $("#loaderText").text('Listo').promise().done(function(){

                            setTimeout(function () {
                                $(".ring").hide(function(){
                                    $(".arrow").show();
                                }) 
                            }, 2000);

                            
                        });
                    }
                    else{
                        alert("Error al procesar la solicitud");
                    }
                })
                .fail(function(response){ alert("Error en el servidor, no pudo procesarse la solicitud") })
                .always(function(){ 
                    //$(".ring").hide() 
                });
            });
            
        });

        function resetForm(){
            $("#formContainer,.arrow, .ring").hide();
            $("#loaderText").text('Scaning')
            $("#lineLoader, .ring").removeClass("hidden");
            $("#registerMobile").show();
            $('.fog').css('display', 'none');
        }
    </script>


    <body>
        <div class="fog"></div>
        <div class="container">
            <div class="row align-items-center justify-content-center mt-2">
                <div class="col-2">Enrutame!</div>
            </div>
        </div>

        <div id="map-img">
            <img src="images/tmap.png" alt="mapa" style='width: 100%' usemap="#mapper">

            <map id="mapper" name="mapper">
                <area class="mapZone" href='#' shape="rect" alt="Current" coords="13,14,510,241">
                <area class="mapZone" href='#' shape="rect" alt="room 1" coords="527,16,950,245">
                <area class="mapZone" href='#' shape="rect" alt="room 2" coords="961,16,1277,238">
                <area class="mapZone" href='#' shape="rect" alt="room 3" coords="1089,259,1285,406">
            </map>

        </div>

        <div id="formContainer" class="container leFont">

            <div class="row justify-content-end mt-4">
                <div class="col-6 align-self-center">Destino: <span id="routeDestiny"><span></div>
                <div class="col-1 align-self-end"><img id="closeForm" src="images/cancel.png" alt="cerrar"></div>
            </div>

            <div id="registerMobile">LLEVAME</div>
            <div class="ring leFont"><label id="loaderText">Scaning</label><span id="lineLoader"></span></div>
            <div class="arrow"></div>

        </div>

    </body>
    

</html>